services:
    - docker

addons:
    apt:
        packages:
            # - docker-ce
            - clang-format
            # - libboost-all-dev
            # - libgmp3-dev
            # - libprocps-dev
            # - g++
            # - libxslt-dev
            # - cmake
            # - libssl-dev
            # - pkg-config
            # - curl
            # - python3.7-venv
            - build-essential
            - autoconf
            - libtool
    homebrew:
        packages:
            - gmp
            - grpc
            - protobuf
            - boost
            - openssl
            - cmake
            - libtool
            - autoconf
            - automake
            - python
            # - llvm

matrix:
    include:
        - env: CI_CONFIG=Release CI_USE_DOCKER=1
          os: linux
          dist: bionic
          language: minimal
        - env: CI_CHECK_FORMAT=1 CI_USE_DOCKER=1 CI_CONFIG=Debug
          os: linux
          dist: bionic
          language: minimal
        - env: CI_CONFIG=Release
          os: osx
          python: 3.7
          osx_image: xcode11
        - env: CI_CONFIG=Debug
          os: osx
          python: 3.7
          osx_image: xcode11

script: CI_USE_DOCKER=${CI_USE_DOCKER} travis_wait 30 scripts/ci ${CI_CONFIG}
